services:

    dapr-placement:
      image: daprio/dapr:1.16.0
      container_name: nats-lab-dapr-placement
      command: ["./placement", "-port", "50006"]
      ports:
        - 50006:50006

    dapr-scheduler:
      image: daprio/dapr:1.16.0
      container_name: nats-lab-dapr-scheduler
      command: ["./scheduler"]
      ports:
        - 50007:50006
      volumes:
        - dapr-scheduler-data:/data

    postgres:
      image: postgres:16-alpine
      container_name: nats-lab-postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=dapr
        - POSTGRES_PASSWORD=dapr
        - POSTGRES_DB=dapr_state
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U dapr -d dapr_state"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  dapr-scheduler-data:
  postgres-data: